services:
  nashvillebarrelco-server:
    build: .
    command: node server.js
    restart: unless-stopped
    env_file: nashvillebarrelco.env
    environment:
      - TZ=America/New_York
    networks:
      - proxy
      - nashvillebarrelco-internal
      - shopify-egress
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.nashvillebarrelco.rule=Host(`nashvillebarrelco.linger.dev`)"
      - "traefik.http.routers.nashvillebarrelco.entrypoints=websecure"
      - "traefik.http.routers.nashvillebarrelco.tls.certresolver=leresolver"
      - "traefik.http.services.nashvillebarrelco.loadbalancer.server.port=3000"

      # HTTP router + redirect middleware
      - "traefik.http.routers.nashvillebarrelco-http.rule=Host(`nashvillebarrelco.linger.dev`)"
      - "traefik.http.routers.nashvillebarrelco-http.entrypoints=web"
      - "traefik.http.routers.nashvillebarrelco-http.middlewares=redirect-to-https"

      # Redirect middleware definition
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=false"

  nashvillebarrelco-watcher:
    build: .
    command: node watcher.js
    restart: unless-stopped
    env_file: nashvillebarrelco.env
    environment:
      - TZ=America/New_York
    volumes:
      - nashvillebarrelco-data:/data
    networks:
      - nashvillebarrelco-internal
      - shopify-egress
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  shopify-egress:
    external: true
  proxy:
    external: true
  nashvillebarrelco-internal:

volumes:
  nashvillebarrelco-data:
