services:
  whiskeyblendery-server:
    build: .
    command: node server.js
    restart: unless-stopped
    env_file: whiskeyblendery.env
    environment:
      - TZ=America/New_York
    networks:
      - proxy
      - whiskeyblendery-internal
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.whiskeyblendery.rule=Host(`whiskeyblendery.linger.dev`)"
      - "traefik.http.routers.whiskeyblendery.entrypoints=websecure"
      - "traefik.http.routers.whiskeyblendery.tls.certresolver=leresolver"
      - "traefik.http.services.whiskeyblendery.loadbalancer.server.port=3000"

      # HTTP router + redirect middleware
      - "traefik.http.routers.whiskeyblendery-http.rule=Host(`whiskeyblendery.linger.dev`)"
      - "traefik.http.routers.whiskeyblendery-http.entrypoints=web"
      - "traefik.http.routers.whiskeyblendery-http.middlewares=redirect-to-https"

      # Redirect middleware definition
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=false"

  whiskeyblendery-watcher:
    build: .
    command: node watcher.js
    restart: unless-stopped
    env_file: whiskeyblendery.env
    environment:
      - TZ=America/New_York
    volumes:
      - whiskeyblendery-data:/data
    networks:
      - whiskeyblendery-internal
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  proxy:
    external: true
  whiskeyblendery-internal:

volumes:
  whiskeyblendery-data:
