services:
  bourbondirect-server:
    build: .
    command: node server.js
    restart: unless-stopped
    env_file: bourbondirect.env
    environment:
      - TZ=America/New_York
    networks:
      - proxy
      - bourbondirect-internal
      - shopify-egress
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.bourbondirect.rule=Host(`bourbondirect.linger.dev`)"
      - "traefik.http.routers.bourbondirect.entrypoints=websecure"
      - "traefik.http.routers.bourbondirect.tls.certresolver=leresolver"
      - "traefik.http.services.bourbondirect.loadbalancer.server.port=3000"

      # HTTP router + redirect middleware
      - "traefik.http.routers.bourbondirect-http.rule=Host(`bourbondirect.linger.dev`)"
      - "traefik.http.routers.bourbondirect-http.entrypoints=web"
      - "traefik.http.routers.bourbondirect-http.middlewares=redirect-to-https"

      # Redirect middleware definition
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=false"

  bourbondirect-watcher:
    build: .
    command: node watcher.js
    restart: unless-stopped
    env_file: bourbondirect.env
    environment:
      - TZ=America/New_York
    volumes:
      - bourbondirect-data:/data
    networks:
      - bourbondirect-internal
      - shopify-egress
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  shopify-egress:
    external: true
  proxy:
    external: true
  bourbondirect-internal:

volumes:
  bourbondirect-data:
